export const resourceConfigs = [
  {
    key: 'profile',
    title: 'Profiles',
    endpoint: 'profile',
    fields: [
      { name: 'user', label: 'User', type: 'number' },
      { name: 'full_name', label: 'Full name', type: 'text' },
      { name: 'bio_summary', label: 'Bio summary', type: 'textarea' },
      { name: 'resume_link', label: 'Resume URL', type: 'text' },
      { name: 'profile_picture', label: 'Profile photo (upload)', type: 'file' },
      { name: 'profile_picture_url', label: 'Profile photo URL', type: 'text' },
      { name: 'location', label: 'Location', type: 'text' },
    ],
  },
  {
    key: 'technologies',
    title: 'Technologies',
    endpoint: 'technologies',
    fields: [{ name: 'name', label: 'Technology name', type: 'text' }],
  },
  {
    key: 'projects',
    title: 'Projects',
    endpoint: 'projects',
    fields: [
      { name: 'user', label: 'Profile', type: 'number' },
      { name: 'title', label: 'Title', type: 'text' },
      { name: 'description', label: 'Description', type: 'textarea' },
      {
        name: 'technologies',
        label: 'Technologies (comma-separated)',
        type: 'array',
      },
      { name: 'live_link', label: 'Live URL', type: 'text' },
      { name: 'github_link', label: 'GitHub URL', type: 'text' },
      { name: 'image', label: 'Image URL', type: 'text' },
      { name: 'display_order', label: 'Display order', type: 'number' },
    ],
  },
  {
    key: 'skills',
    title: 'Skills',
    endpoint: 'skills',
    fields: [
      { name: 'user', label: 'Profile', type: 'number' },
      { name: 'name', label: 'Skill name', type: 'text' },
      {
        name: 'proficiency_level',
        label: 'Proficiency',
        type: 'select',
        options: [
          { value: 'beg', label: 'Beginner' },
          { value: 'int', label: 'Intermediate' },
          { value: 'adv', label: 'Advanced' },
        ],
      },
      { name: 'category', label: 'Category', type: 'text' },
      { name: 'certification_url', label: 'Certification URL', type: 'text' },
    ],
  },
  {
    key: 'experience',
    title: 'Experience',
    endpoint: 'experience',
    fields: [
      { name: 'user', label: 'Profile', type: 'number' },
      { name: 'job_title', label: 'Job title', type: 'text' },
      { name: 'company_name', label: 'Company name', type: 'text' },
      { name: 'start_date', label: 'Start date', type: 'date' },
      { name: 'end_date', label: 'End date', type: 'date' },
      { name: 'responsibilities', label: 'Responsibilities', type: 'textarea' },
      { name: 'is_current', label: 'Current role', type: 'checkbox' },
    ],
  },
  {
    key: 'messages',
    title: 'Messages',
    endpoint: 'messages',
    fields: [
      { name: 'sender_name', label: 'Sender name', type: 'text', readOnly: true },
      { name: 'sender_email', label: 'Sender email', type: 'text', readOnly: true },
      { name: 'subject', label: 'Subject', type: 'text', readOnly: true },
      { name: 'message_content', label: 'Message', type: 'textarea', readOnly: true },
      { name: 'is_read', label: 'Mark as read', type: 'checkbox' },
      {
        name: 'response_status',
        label: 'Response status',
        type: 'select',
        options: [
          { value: 'new', label: 'New' },
          { value: 'progress', label: 'In progress' },
          { value: 'responded', label: 'Responded' },
        ],
      },
      { name: 'response_text', label: 'Response notes', type: 'textarea' },
    ],
  },
]
